
spring:
    application.name: planner-data-access
    datasource:
      url: jdbc:postgresql://postgres:5432/planner-data-access
      username: postgres
      password: postgres
    jpa.hibernate.ddl-auto: update

server.port: 8080

spring.zipkin.base-url: http://zipkin:9411/

    ## PostgreSQL
    #spring.jpa.database=POSTGRESQL
    #spring.datasource.platform=postgres
    #spring.datasource.driver-class-name=org.postgresql.Driver


spring.cloud.stream.kafka.binder.brokers: kafka:9092

spring.cloud.stream.bindings.realms-events.destination: realms-events
spring.cloud.stream.bindings.realms-events.contentType: application/json

spring.cloud.stream.bindings.targets-events.destination: targets-events
spring.cloud.stream.bindings.targets-events.contentType: application/json

spring.cloud.stream.bindings.means-events.destination: means-events
spring.cloud.stream.bindings.means-events.contentType: application/json

spring.cloud.stream.bindings.layers-events.destination: layers-events
spring.cloud.stream.bindings.layers-events.contentType: application/json

  #spring.cloud.stream.bindings.api-gateway-bm-out.destination=api-gateway-bm
  #spring.cloud.stream.bindings.api-gateway-bm-out.contentType=application/json

logging.file.name: logs/data-access.log