
spring:
    application.name: planner-data-access
    datasource:
      url: jdbc:postgresql://postgres:5432/planner_data_access
      username: postgres
      password: postgres
    jpa.hibernate.ddl-auto: update

server.port: 8080

spring.zipkin.base-url: http://zipkin:9411/

    ## PostgreSQL
    #spring.jpa.database=POSTGRESQL
    #spring.datasource.platform=postgres
    #spring.datasource.driver-class-name=org.postgresql.Driver


spring.cloud.stream:
  kafka.binder.brokers: kafka-0:9092
  bindings:
    realms-events:
      destination: realms-events
      contentType: application/json
    targets-events:
      destination: targets-events
      contentType: application/json
    means-events:
      destination: means-events
      contentType: application/json
#    layers-events:
#      destination: layers-events
#      contentType: application/json
#    tasks-events:
#      destination: tasks-events
#      contentType: application/json
    mean-target-relations-events:
      destination: mean-target-relations-events
      contentType: application/json

  #spring.cloud.stream.bindings.api-gateway-bm-out.destination=api-gateway-bm
  #spring.cloud.stream.bindings.api-gateway-bm-out.contentType=application/json

logging.file.name: logs/data-access.log
