# syntax = docker/dockerfile:experimental

ARG applicationName
ARG bootCommand=bootJar
ARG jarExt=jar
ARG $APP_VERSION=1.0.0

FROM gradle:7.2-jdk11 as build

ARG bootCommand
ARG applicationName

WORKDIR /workspace/
COPY . .

WORKDIR /workspace/$applicationName

RUN --mount=type=cache,target=/root/.m2/ \
    --mount=type=cache,sharing=locked,target=/root/.gradle \
    gradle --info --no-daemon -s clean $bootCommand -p $applicationName --stacktrace

FROM openjdk:11-jre-slim
ARG applicationName
ARG $APP_VERSION
ARG jarExt
ENV APP_NAME="app.$jarExt"
ENV JAR_FULL_PATH="/opt/software/$applicationName/$APP_NAME"
ENV DEBUG_OPT="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
ENV JAVA_OPTS=""
ENV ENV_NAME="local"

WORKDIR /appdata
COPY --from=build /workspace/$applicationName/build/libs/*.$jarExt $JAR_FULL_PATH
EXPOSE 8080 5005
ENTRYPOINT ["sh", "-c", "java $DEBUG_OPT $JAVA_OPTS -Dspring.profiles.active=$ENV_NAME -Dinfo.app.env=$ENV_NAME -jar $JAR_FULL_PATH"]
