version: '3.4'
services:
    api-gateway:
        image: planner2/api-gateway:0.0.1
        ports:
            - "8090:8080"
        #        network_mode: host
        volumes:
            - /home/alex/installs/planner2/logback:/workspace/logs
#        depends_on:
#            - kafka

    realms-service:
        image: planner2/realms-service:0.0.1
        ports:
            - "8091:8080"
        volumes:
            - /home/alex/installs/planner2/logback:/workspace/logs
#        depends_on:
#            - postgres
#            - kafka
#        networks:
#            - planner-microservices_subnet_1

#networks:
#    planner-microservices_subnet_1:
#        external: true
