version: '3.4'
services:

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
        ports:
            - "9200:9200"
        environment:
            - "discovery.type=single-node"
#        volumes:
#            - /home/alex/installs/planner2/elasticsearch/data:/usr/share/elasticsearch/data

    kibana:
        image: docker.elastic.co/kibana/kibana:7.2.0
        ports:
            - "5601:5601"
        restart: on-failure
        depends_on:
            - elasticsearch

    logstash:
        image: docker.elastic.co/logstash/logstash:7.0.0
        volumes:
            - /home/alex/Projects/planner-microservices/config:/home/alex/Projects/planner-microservices/config
            - /home/alex/installs/planner2/logback:/home/alex/installs/planner2/logback
        command: logstash -f /home/alex/Projects/planner-microservices/config/logstash.conf
        depends_on:
            - elasticsearch

    zipkin:
        image: openzipkin/zipkin
        ports:
            - "9411:9411"
