version: '3.4'
services:
    postgres:
        image: postgres:9.4
        ports:
            - "5433:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /data/postgres
        volumes:
            - /home/alex/installs/planner2/postgres-data:/data/postgres
#        networks:
#            - planner-microservices_subnet_1

#networks:
#    planner-microservices_subnet_1:
#        external: true
