
spring.application:
    name: planner-api-gateway

server.port: 8080

spring.zipkin.base-url: http://zipkin:9411/

spring.cloud.stream.kafka.binder.brokers: kafka-0:9092

spring.cloud.stream.bindings.realms-in.destination: realms-in
spring.cloud.stream.bindings.realms-in.contentType: application/json

  #spring.cloud.stream.bindings.api-gateway-bm-out.destination=api-gateway-bm
  #spring.cloud.stream.bindings.api-gateway-bm-out.contentType=application/json

service.name: planner-api-gateway
services.realms.url: http://realms-service:8080

logging.file.name: logs/api-gateway.log

zuul:
    routes:
        realms/get:
            path: /realms/get/**
            url: http://data-access:8080
            stripPrefix: false
        targets/get:
            path: /targets/get/**
            url: http://data-access:8080
            stripPrefix: false
        means/get:
            path: /means/get/**
            url: http://data-access:8080
            stripPrefix: false
        tasks/get:
            path: /tasks/get/**
            url: http://data-access:8080
            stripPrefix: false
        layers/get:
            path: /layers/get/**
            url: http://data-access:8080
            stripPrefix: false
        realms:
            path: /realms/**
            url: http://realms-service:8080
            stripPrefix: false
        targets:
            path: /targets/**
            url: http://targets-service:8080
            stripPrefix: false
        means:
            path: /means/**
            url: http://means-service:8080
            stripPrefix: false