apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: es
        image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
        env:
        - name: discovery.type
          value: single-node

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 30123
  selector:
    app: elasticsearch

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kib
          image: docker.elastic.co/kibana/kibana:7.2.0

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  type: NodePort
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30124
  selector:
    app: kibana

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: ls
          image: docker.elastic.co/logstash/logstash:7.0.0
          volumeMounts:
            - name: config
              mountPath: /usr/share/logstash/pipeline/
          command:
            - logstash
      volumes:
        - name: config
          configMap:
            name: logstash-config
            items:
              - key: logstash.conf
                path: logstash.conf

---
apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30125
  selector:
    app: logstash