apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: hw
        image: planner2/helloworld:0.0.1
