apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: hw
        image: planner2/helloworld:0.0.1
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /version
            port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30126
  selector:
    app: helloworld