apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.4
        env:
         - name: POSTGRES_USER 
           value: postgres
         - name: POSTGRES_PASSWORD
           value: postgres
         - name: PGDATA
           value: /data/postgres
        volumeMounts:
         - name: config
           mountPath: /docker-entrypoint-initdb.d/
           readOnly: true
      volumes:
       - name: config
         configMap:
           name: postgres-init
