version: '3.4'
services:
    api-gateway:
        image: planner2/api-gateway:0.0.1
        ports:
            - "8090:8080"
        #        network_mode: host
        volumes:
            - ${logsPath}:/workspace/logs
#        depends_on:
#            - kafka

    realms-service:
        image: planner2/realms-service:0.0.1
#        ports:
#            - "8091:8080"
        volumes:
            - ${logsPath}:/workspace/logs
#        depends_on:
#            - postgres
#            - kafka
#        networks:
#            - planner-microservices_subnet_1

    targets-service:
        image: planner2/targets-service:0.0.1
#        ports:
#            - "8091:8080"
        volumes:
            - ${logsPath}:/workspace/logs

    means-service:
        image: planner2/means-service:0.0.1
        #        ports:
        #            - "8091:8080"
        volumes:
            - ${logsPath}:/workspace/logs

    data-access:
        image: planner2/data-access-service:0.0.1
        ports:
            - "8092:8080"
        volumes:
            - ${logsPath}:/workspace/logs
#        depends_on:
#            - postgres
#            - kafka

#networks:
#    planner-microservices_subnet_1:
#        external: true
