version: '3.4'
services:

    targets-service:
        image: planner2/targets-service:0.0.1
#        ports:
#            - "8091:8080"
        volumes:
            - /home/alex/installs/planner2/logback:/workspace/logs