version: '3.4'
services:

    #----------Services--------------
    api-gateway:
        image: planner2/api-gateway:0.0.1
        ports:
            - "8090:8080"
#        network_mode: host
        volumes:
            - /home/alex/installs/planner2/logback:/workspace/logs
        depends_on:
            - kafka

    realms-service:
        image: planner2/realms-service:0.0.1
        ports:
            - "8091:8080"
        volumes:
            - /home/alex/installs/planner2/logback:/workspace/logs
        depends_on:
            - postgres
            - kafka

    #----------DB--------------
    postgres:
        image: postgres:9.4
        ports:
            - "5433:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /data/postgres
        volumes:
            - /home/alex/installs/planner2/postgres-data:/data/postgres

    #-----------------kafka--------------------
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
        volumes:
            - /home/alex/installs/planner2/kafka:/kafka

    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 192.168.1.36
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
            - /home/alex/installs/planner2/kafka:/kafka
#            - /var/run/docker.sock:/var/run/docker.sock


    #----------Monitoring--------------
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
        ports:
          - "9200:9200"
        environment:
          - "discovery.type=single-node"
#        volumes:
#          - /home/alex/installs/planner2/elasticsearch/data:/usr/share/elasticsearch/data:rw

    kibana:
        image: docker.elastic.co/kibana/kibana:7.2.0
        ports:
          - "5601:5601"
        restart: on-failure
        depends_on:
          - elasticsearch

    logstash:
        image: docker.elastic.co/logstash/logstash:7.0.0
        volumes:
            - /home/alex/Projects/planner-microservices/config:/home/alex/Projects/planner-microservices/config
            - /home/alex/installs/planner2/logback:/home/alex/installs/planner2/logback
        command: logstash -f /home/alex/Projects/planner-microservices/config/logstash.conf
        depends_on:
            - elasticsearch

    zipkin:
        image: openzipkin/zipkin
        ports:
        - "9411:9411"

#networks:
#    loggin-net: {}
