
spring.application.name: planner-means

server.port: 8080

spring.zipkin.base-url: http://zipkin:9411/

    ## PostgreSQL
    #spring.jpa.database=POSTGRESQL
    #spring.datasource.platform=postgres
    #spring.datasource.driver-class-name=org.postgresql.Driver


spring.cloud.stream.kafka.binder.brokers: kafka:9092

spring.cloud.stream.bindings.means-events.destination: means-events
spring.cloud.stream.bindings.means-events.contentType: application/json

spring.cloud.stream.bindings.layers-events.destination: layers-events
spring.cloud.stream.bindings.layers-events.contentType: application/json

spring.cloud.stream.bindings.tasks-events.destination: tasks-events
spring.cloud.stream.bindings.tasks-events.contentType: application/json

  #spring.cloud.stream.bindings.api-gateway-bm-out.destination=api-gateway-bm
  #spring.cloud.stream.bindings.api-gateway-bm-out.contentType=application/json

services.data-access-service.url: http://data-access:8080

logging.file.name: logs/means.log