
spring.application.name: planner-targets

server.port: 8080

spring.zipkin.base-url: http://zipkin:9411/

spring.cloud.stream:
  kafka.binder.brokers: kafka-0:9092
  bindings:
    realms-events:
      destination: realms-events
      contentType: application/json
    targets-events:
      destination: targets-events
      contentType: application/json

services.data-access-service.url: http://data-access:8080

logging.file.name: logs/targets.log